### ISSUE TITLE
DatePicker withTimePicker

### ISSUE THREAD

**Issue by bobingham** [valor-software/ng2-bootstrap#6433]
When using the _Datepicker_ with _withTimePicker_ option the only way to set the time is when the initial input value is empty.  You must then set the time before selecting the date.  It is not possible to reset the time after re-opening the date picker, even if the time is changed and a different day is selected the time value will not change.
The problem can be found using the demo on the ngx-bootstrap site (v8.0.0):
[Date-picker-with-time-picker](https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=overview#with-timepicker)

**Comment by TheVoxell** [comment]
Yeah here the same issue. With the previous version timepicker was working fine.

**Comment by paulredert** [comment]
Any update on this?

**Comment by jethas-bennettjones** [comment]
Any update @SvetlanaMuravlova ?

**Comment by jakubdrewniak** [comment]
any updates?

edit: i've found why that happens: it's all because this commit 
https://github.com/valor-software/ngx-bootstrap/commit/12e050fab9b002169051a363a9fe2dc22edbdecc
It looks like  !isNaN(sourceDate.getTime()) for (stringyifed) sourceDate "2022-04-14T12:33:00.000Z"  is true, so function returns undefined and time is not copied to source date. 

I'm not sure about motivation, but another change in this commit is skipping one of helpers test... the one that would fail because of change in helper. It is a part of clear buton fixin but... when I remove whole 
`  if (!sourceDate || !isNaN(sourceDate.getTime())) {
    return;
  }`
clear button still working. @SvetlanaMuravlova @MuravlovaSvetlana do you know what is exact purpose of `!isNaN(sourceDate.getTime())` ?

**Comment by TheVoxell** [comment]
Thanx for the research jakubdrawniak. Now lets hope for a fix soon!

**Comment by Gillardo** [comment]
Any idea on fix time?

**Comment by TheVoxell** [comment]
It is now useless as all clcks on the time will close the popups

**Comment by Gillardo** [comment]
Any news on this, its quite a major bug that the timepicker closes on every click on time component

**Comment by rockyahmed** [comment]
> Any news on this, its quite a major bug that the timepicker closes on every click on time component

Any update this issue ?

**Comment by SvetlanaMuravlova** [comment]
hi all) as i can see, it is fixed in version 9.0.0, when we will get approve from our qa this issue will be closed, so check it please)

**Comment by TheVoxell** [comment]
Unfortunately it is not fixed yet. When cycling the time it closes the popup every time. so my customers should open the popup 1000 times to select the correct time. This is taking very long to fix.

**Comment by SvetlanaMuravlova** [comment]
> Unfortunately it is not fixed yet. When cycling the time it closes the popup every time. so my customers should open the popup 1000 times to select the correct time. This is taking very long to fix.

as I can see, this issue was created regarding another problem and it is fixed. You are talking about native behaviour of the component. I am agree it isn't comfortable to open datepicker every time, but we can discuss it as enhancement in another issue.

**Comment by SvetlanaMuravlova** [comment]
@TheVoxell , i've prepared a pr for resolving your issue, so i hope it will be available in the next release https://github.com/valor-software/ngx-bootstrap/pull/6537

**Comment by rockyahmed** [comment]
> > Any news on this, its quite a major bug that the timepicker closes on every click on time component
> 
> Any update this issue ?

this issue not solved because now when i first select time it's close automatically ?

**Comment by SvetlanaMuravlova** [comment]
> > > Any news on this, its quite a major bug that the timepicker closes on every click on time component
> > 
> > 
> > Any update this issue ?
> 
> this issue not solved because now when i first select time it's close automatically ?

But it isn't bug. You get first closing, cause datepicker closes everytime when date is changed. When you click at first on timepicker without choosing any date it sets default date, so date is changed 
if you need set time without date use please timepicker)

**Comment by Gillardo** [comment]
> > > > Any news on this, its quite a major bug that the timepicker closes on every click on time component
> > > 
> > > 
> > > Any update this issue ?
> > 
> > 
> > this issue not solved because now when i first select time it's close automatically ?
> 
> But it isn't bug. You get first closing, cause datepicker closes everytime when date is changed. When you click at first on timepicker without choosing any date it sets default date, so date is changed if you need set time without date use please timepicker)

How is it not a bug when the popup closes everytime you try to pick a time, when using date and time.

**Comment by Gillardo** [comment]
Why has this been closed?

**Comment by SvetlanaMuravlova** [comment]
> > > > > Any news on this, its quite a major bug that the timepicker closes on every click on time component
> > > > 
> > > > 
> > > > Any update this issue ?
> > > 
> > > 
> > > this issue not solved because now when i first select time it's close automatically ?
> > 
> > 
> > But it isn't bug. You get first closing, cause datepicker closes everytime when date is changed. When you click at first on timepicker without choosing any date it sets default date, so date is changed if you need set time without date use please timepicker)
> 
> How is it not a bug when the popup closes everytime you try to pick a time, when using date and time.

Can you add please some reproducing of this bug, now we can see behaviour as expected   https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=overview#close-behavior

**Comment by Gillardo** [comment]
- Open demo
- Go to WithTimePicker demo 
https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=overview#with-timepicker
- Now try picking a time

Keeps closing everytime you do anything with time, unless you manually type it in

**Comment by SvetlanaMuravlova** [comment]
> * Open demo
> * Go to WithTimePicker demo
>   https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=overview#with-timepicker
> * Now try picking a time
> 
> Keeps closing everytime you do anything with time, unless you manually type it in

as i mentioned below, try this link https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=overview#close-behavior

**Comment by ahijaouy** [comment]
@SvetlanaMuravlova, using the demo widget you linked to there is still an issue.

On the first interaction with the time widget, it still auto closes. On all subsequent interactions with the time widget, it stays open. 

See video for the repro

https://user-images.githubusercontent.com/14722764/210402995-cd8b8d10-d993-40cb-adc5-ac9ba590e0c5.mov

**Comment by SvetlanaMuravlova** [comment]
> @SvetlanaMuravlova, using the demo widget you linked to there is still an issue.
> 
> On the first interaction with the time widget, it still auto closes. On all subsequent interactions with the time widget, it stays open.
> 
> See video for the repro
> 
>  Screen.Recording.2023-01-03.at.8.50.21.AM.mov

thank you for your description, but as i mentioned below, it isn't bug. It is a native behaviour for datepicker, it closes everytime, when date is changed, at first, when you choose only time, it sets default date, so because of it closes at first. Datepicker doesn't work only with time, in this way you should use timepicker separately. It will be changed after component refactoring little bit later, now it was implemented, to make using of datepicker with timepicker more comfortable

**Comment by Nvveen** [comment]
How is it normal to have to open the datepicker three times in a row? To change a date, to change the hour and to change the minute? This is ridiculous, if there's an option to keep the datepicker open, then it should remain open. Right now, our only option is to have a separate datepicker on an <input /> element, and then use the timepicker inline element next to it, complete defeating the point of the "withTimepicker" option in the datepicker directive.

Edit: For anyone who also thinks this isn't how it is supposed to work and doesn't mind a giant hack; if you get a reference to the DatepickerDirective (I am using host directives), after init set this: `this._datepicker.keepDatepickerModalOpened = () => true;` or any variation (for example, only closing when minutes or hours change).
