### ISSUE TITLE
ng add ngx-bootstrap giving error Cannot find module 'C:\Workspace\angular-demo\node_modules\@schematics\angular\utility\test.js'

### ISSUE THREAD

**Issue by nitin27may** [valor-software/ng2-bootstrap#6509]
I create a new Angular project by runnning command `ng new angular-demo` after that I am trying to run command `ng add ngx-bootstrap`. It is installing ngx-bootstrap 9.0.0 but then giving error and not updating all required configuration: 

![image](https://user-images.githubusercontent.com/8065536/190680665-2a1329e7-d016-4ef9-be66-b05588477754.png)

 

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 9.0.0

Angular: 14.2.0

Bootstrap: Not added as `ng add ngx-bootstrap` is broken

Build system: 
Angular CLI: 14.2.3
Node: 16.14.0
Package Manager: npm 8.19.1
OS: win32 x64

**Expected behavior**

It should add all dpendeicies and update the configuration.

**Comment by matheuscabralsz** [comment]
having the same issue here, same build system as yours

**Comment by SvetlanaMuravlova** [comment]
@matheuscabralkk , @nigelsim hi) thank you for your issue. It should be fixed in this pr https://github.com/valor-software/ngx-bootstrap/pull/6508
connected issue #6505

**Comment by Rich-Hopkins** [comment]
I see that the PR is to fix this issue, and it was 21 days ago, but I still have the same issue. I asked the question in the slack group on 9/27, and no responses there, so I'm posting here. How do I get this PR when I do npm add ngx-bootstrap?

**Comment by GunnysKid** [comment]
> I have this same issue. I see that PR 6508 fixed it, but I don't see what I need to do to get it working. I've asked in the slack group, and I see a StackOverflow question that doesn't have a helpful answer, so no point in asking the same thing again there. What do I need to do in order to get the code that works?

I'm having the same issue. I'm seeing that it's "fixed" in multiple pull requests here that keep referencing each other, but no clue on how or what to do to proceed. Details beside "its fixed in this pr" would be greatly appreciated.

**Comment by SvetlanaMuravlova** [comment]
@GunnysKid new version with this pr hasn't been released yet ))

**Comment by Rich-Hopkins** [comment]
@SvetlanaMuravlova any idea when we can expect that release?

**Comment by Rich-Hopkins** [comment]
@SvetlanaMuravlova , it's been a month since I last asked, will this fix be released anytime soon?

**Comment by zoleko** [comment]
same issue in 2023 
is there a fix for this please
I can see version 10.x.x is for angular 15.x.x
