### ISSUE TITLE
Datepicker broken when running Zoneless

### ISSUE THREAD

**Issue by FrancescoBorzi** [valor-software/ng2-bootstrap#6780]
Bug description:

When using Angular in Zoneless mode (which is going to be the default in Angular 21) the Datepicker no longer works and I see this error in the console:

```
chunk-error.handler.ts:14 ERROR RuntimeError: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for '@datepickerAnimation': 'void'. Current value: 'unanimated'. Expression location: _BsDatepickerContainerComponent component. Find more at https://v20.angular.dev/errors/NG0100
```

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: `20.0.2`

Angular: 20

Bootstrap: `4.6.2`

Build system: Angular CLI, System.js, webpack, starter seed: NX

**Expected behavior**

It should work with Zoneless

**Comment by Francesco-Borzi** [comment]
I wrote an ugly hackfix directive to make it work:

```typescript
import { DestroyRef, Directive, inject } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { BsDatepickerDirective } from 'ngx-bootstrap/datepicker';

@Directive({
  // eslint-disable-next-line @angular-eslint/directive-selector
  selector: '[datepickerZonelessHackfix]',
})
export class DatepickerZonelessHackfixDirective {
  private readonly dp = inject(BsDatepickerDirective);
  private readonly destroyRef = inject(DestroyRef);

  private mouseX = 0;
  private mouseY = 0;

  constructor() {
    window.addEventListener(
      'pointermove',
      (e) => {
        this.mouseX = e.clientX;
        this.mouseY = e.clientY;
      },
      { passive: true },
    );

    this.dp.onShown.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => this.triggerPositioning());

    // needed if another datepicker is opened before closing this one
    this.dp.onHidden.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => this.triggerPositioning());
  }

  private triggerPositioning(): void {
    this.waitForDatepickerContainer()
      .then((container) => {
        requestAnimationFrame(() => this.positionContainerAtMouse(container));
      })
      .catch();
  }

  private waitForDatepickerContainer(timeoutMs = 1500): Promise<HTMLElement> {
    const containerSelector = 'bs-datepicker-container';
    const existing = document.querySelector<HTMLElement>(containerSelector);
    if (existing) return Promise.resolve(existing);

    return new Promise((resolve, reject) => {
      const obs = new MutationObserver(() => {
        const element = document.querySelector<HTMLElement>(containerSelector);
        if (element) {
          obs.disconnect();
          resolve(element);
        }
      });
      obs.observe(document.body, { childList: true, subtree: true });
      setTimeout(() => {
        obs.disconnect();
        reject(new Error('bs-datepicker-container not found in time'));
      }, timeoutMs);
    });
  }

  private positionContainerAtMouse(container: HTMLElement): void {
    container.style.display = 'block';
    container.style.position = 'absolute';
    container.style.willChange = 'transform';
    container.style.top = '0px';
    container.style.left = '0px';
    const x = this.mouseX;
    const y = this.mouseY;
    container.style.transform = `translate3d(${x}px, ${y}px, 0px)`;
  }
}
```

To be used like this:

```html
<input
  [bsConfig]="{ dateInputFormat: 'DD-MM-YYYY', isAnimated: false, adaptivePosition: false }"
  datepickerZonelessHackfix
  bsDatepicker
/>
```

**Comment by alexeysalesintel** [comment]
Html
```
<input bsDatepicker type="text"/>
```
Component ts
```
export class FormDateInputComponent implements AfterViewInit {
    @ViewChild(BsDatepickerDirective, { static: true })
    dt: BsDatepickerDirective;

    private scroll$: Observable<Event> = fromEvent(document, 'scroll', { capture: true, passive: true });

   constructor(private zone: NgZone) {}

   private recalculatePosition() {
        const componentLoader: ComponentLoader<BsDatepickerContainerComponent> = this.dt['_datepicker'];

        if (componentLoader) {
            componentLoader.instance['_positionService'].event$.pipe(take(1)).subscribe(() => {
                componentLoader.instance['_positionService'].enable();
                componentLoader._componentRef.changeDetectorRef.markForCheck();
                this.zone.onStable.emit();
            });
        }
    }

   ngAfterViewInit(): void {
          this.dt.onShown.pipe(
              tap(() => this.scroll$.pipe(tap(() => requestAnimationFrame(() => this.recalculatePosition())), takeUntil(this.dt.onHidden)).subscribe()),
              tap(() => this.recalculatePosition()),
              untilDestroyed(this)
          ).subscribe();
    }
}
```

I investigated source code of datePicker, this code will fix through change detection, without zone. Also I recalculated repsitioning on any page scroll. Note that in this case zone: NgZone, it is just existing NoopNgZone realization in zoneless app
@Francesco-Borzi

**Comment by sherlock1982** [comment]
Basically what's not working is any component with `container=body`. For me it's not only dayepicker but also tooltip and dropdowns.

**Comment by vladt22** [comment]
Combining the two hacks above, tested in ng21 zoneless and "ngx-bootstrap": "^21.0.1"

```
import { DestroyRef, Directive, inject, NgZone } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ComponentLoader } from 'ngx-bootstrap/component-loader';
import { BsDatepickerContainerComponent, BsDatepickerDirective } from 'ngx-bootstrap/datepicker';
import { fromEvent, Observable, take, takeUntil, tap } from 'rxjs';

// based on https://github.com/valor-software/ngx-bootstrap/issues/6780
@Directive({
  selector: '[bsDpFix]',
})
export class BsDatepickerFix {
  private readonly dp = inject(BsDatepickerDirective);
  private readonly destroyRef = inject(DestroyRef);

  private scroll$: Observable<Event> = fromEvent(document, 'scroll', { capture: true, passive: true });

  constructor(private zone: NgZone) {
    this.dp.onShown
      .pipe(
        tap(() =>
          this.scroll$
            .pipe(
              tap(() => requestAnimationFrame(() => this.recalculatePosition())),
              takeUntil(this.dp.onHidden),
            )
            .subscribe(),
        ),
        tap(() => this.recalculatePosition()),
        takeUntilDestroyed(this.destroyRef),
      )
      .subscribe();
  }

  private recalculatePosition() {
    const componentLoader: ComponentLoader<BsDatepickerContainerComponent> = this.dp['_datepicker'];

    if (componentLoader) {
      componentLoader.instance!['_positionService'].event$.pipe(take(1)).subscribe(() => {
        componentLoader.instance!['_positionService'].enable();
        componentLoader._componentRef!.changeDetectorRef.markForCheck();
        this.zone.onStable.emit();
      });
    }
  }
}

```

**Comment by DerekLiang** [comment]
I tested and confirmed that #6789  would fix the issue. No additional directive is needed.

**Comment by lexasq** [comment]
Fixed with migration to zoneless in v21.2

**Comment by steffbeckers** [comment]
I'm on Angular 21.2.13 & ngx-bootstrap 21.2.0, but still get the following error in console:

```
RuntimeError: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for '@datepickerAnimation': 'void'. Current value: 'unanimated'. Expression location: _BsDaterangepickerInlineContainerComponent component. Find more at https://v21.angular.dev/errors/NG0100
```

**Comment by steffbeckers** [comment]
@lexasq I've created an example in [StackBlitz](https://stackblitz.com/edit/angular-21-ngx-bootstrap-cewtrqno?file=src%2Fmain.ts). When you load the page, just click the navigate link directly and check the console error. After hovering over or using the datepicker, the navigate doesn't throw an error anymore.
